buildscript {
    // تعريف المتغير هنا هو الحل السحري
    ext.kotlin_version = '1.9.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // تحديث أدوات أندرويد لتتوافق مع Gradle 7.6.3
        classpath 'com.android.tools.build:gradle:7.4.2'
        // استخدام إصدار كوتلين المعرف بالأعلى
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

