name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. سحب الكود
    - uses: actions/checkout@v4

    # 2. إعداد جافا (الإصدار 17 هو الأفضل حالياً)
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. إعداد فلاتر
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    # 4. خطوة سحرية: إصلاح ملفات الأندرويد إذا كانت ناقصة
    - run: flutter create --platforms android .

    # 5. تحميل المكتبات
    - run: flutter pub get

    # 6. خطوة هامة جداً: إعطاء صلاحية التنفيذ لملف جرادل (يحل مشكلة الفشل الصامت)
    - name: Fix Gradle Permissions
      run: chmod +x android/gradlew

    # 7. بناء ملف APK
    - run: flutter build apk --release

    # 8. رفع الملف لكي تقوم بتحميله
    - uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk

